# Generated by Django 5.2.15 on 2026-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contributor_name',
            field=models.CharField(blank=True, help_text='Name of contributor if not a registered platform user.', max_length=100, null=True),
        ),
    ]
