# Generated by Django 5.2.15 on 2026-07-27 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership'),
        ('fundraisers', '0003_contribution_contributor_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contributor__isnull', True), _negated=True), models.Q(('contributor_name__isnull', True), _negated=True), _connector='OR'), name='contribution_has_identity'),
        ),
    ]
