# Generated by Django 5.2.15 on 2026-07-27 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership'),
        ('fundraisers', '0004_contribution_contribution_has_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text="Public label e.g. 'The Omondi Family' or 'Baby Jane Medical Fund'", max_length=200)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('education', 'Education'), ('funeral', 'Funeral/Bereavement'), ('disaster', 'Disaster Relief'), ('other', 'Other')], default='other', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(blank=True, help_text='National ID or passport — for payout verification and fraud prevention', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('relationship_to_org', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
