# Generated by Django 5.2.15 on 2026-07-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership'),
        ('fundraisers', '0005_beneficiary'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='beneficiary',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id__isnull', False)), fields=('organization', 'national_id'), name='unique_national_id_per_org'),
        ),
    ]
