# Generated by Django 5.2.15 on 2026-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0007_fundraiserbeneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='public_description',
            field=models.TextField(blank=True, default='', help_text="Public-facing context shown to members e.g. 'Mama Wanjiku needs support for kidney surgery'"),
        ),
    ]
